# Generated by Django 5.2.3 on 2025-09-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='id',
        ),
        migrations.AddField(
            model_name='work',
            name='todoid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
